# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PokéMatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

  # Pods for PokéMatch
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'Firebase/Messaging'
pod 'Google-Mobile-Ads-SDK'

target 'PokéMatchTests' do
inherit! :search_paths
    # Pods for testing
end

target 'PokéMatchUITests' do
inherit! :search_paths
    # Pods for testing
end

end

